#!/usr/bin/env python3
"""Turn splat's disassembly of hand-written code into assembly source.

Code that was written in assembly (not compiler output) is kept as a .s
file under src/ instead of INCLUDE_ASMs in a .c file:

  asm_source.py src/main/<name>.s
      tidy the file splat wrote for a hasm segment, in place
  asm_source.py src/main/psyq/<object>.c
      write src/main/psyq/<object>.s from the INCLUDE_ASMs and
      INCLUDE_RODATAs of that PsyQ object (asm/<version>/ has to be
      generated, VERSION as for make, us by default), for
      the build to take in place of the .c; delete the .c afterwards

Tidying drops splat's ROM/VRAM/bytes comments, its `nonmatching` markers
and its guesses about which instructions are hand-written: the file is the
source now, not a disassembly to be replaced. The evidence that the code
is hand-written goes in a comment at the top.
"""

import re
import sys
from pathlib import Path

from version import ASM_DIR

ADDRESS = re.compile(r"/\* [0-9A-F]+ [0-9A-F]+(?: [0-9A-F]+)? \*/  ?")
DROP = re.compile(
    r"^\s*(nonmatching\s|/\* Generated by spimdisasm|/\* Handwritten function \*/)"
)
INCLUDE = re.compile(r"^INCLUDE_(ASM|RODATA)\(\s*\"([^\"]+)\"\s*,\s*(\w+)\s*\);")
OBJECT_END = re.compile(r"^OBJECT_END\((\d+)\);")


def tidy(lines: list) -> list:
    out = []
    for line in lines:
        if DROP.match(line):
            continue
        line = ADDRESS.sub("", line)
        line = re.sub(r" /\* (handwritten|invalid) instruction \*/", "", line).rstrip()
        # no more than one blank line in a row
        if not line and (not out or not out[-1]):
            continue
        out.append(line)
    while out and not out[-1]:
        out.pop()
    return out


def header(comment: str) -> list:
    return [comment.rstrip(), "", '.include "macro.inc"', "", ".set noat", ".set noreorder", ""]


def from_c(path: Path) -> Path:
    """The .s of the PsyQ object PATH, from what its INCLUDE_ASMs include."""
    text = path.read_text()
    comment = re.match(r"\s*(/\*.*?\*/)", text, re.S)
    body = []
    section = None
    for line in text.splitlines():
        m = INCLUDE.match(line)
        if m:
            kind, folder, name = m.groups()
            want = ".section .text" if kind == "ASM" else ".section .rodata"
            if want != section:
                body += ["", want]
                section = want
            # the folder is relative to the version's asm, as in include_asm.h
            asm = (ASM_DIR / folder / f"{name}.s").read_text().splitlines()
            body += [""] + tidy([l for l in asm if not l.startswith(".set ")])
            continue
        m = OBJECT_END.match(line)
        if m:
            if section != ".section .text":
                body += ["", ".section .text"]
                section = ".section .text"
            body += ["", f"    # ASPSX's padding of the object's .text to 16 bytes", f"    .fill {m.group(1)}, 4, 0"]
            continue
        code = line.strip()
        if code and not code.startswith(("#include", "INCLUDE_", "//", "/*", "*")):
            sys.exit(f"{path}: not only INCLUDE_ASMs: {code!r}")
    top = comment.group(1) if comment else f"/* {path.stem}: written in assembly */"
    out = path.with_suffix(".s")
    out.write_text("\n".join(header(top) + tidy(body)) + "\n")
    return out


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    path = Path(sys.argv[1])
    if path.suffix == ".c":
        print(from_c(path))
    else:
        path.write_text("\n".join(tidy(path.read_text().splitlines())) + "\n")


if __name__ == "__main__":
    main()
