#!/usr/bin/env python3
"""Cut a 1-bit font out of the executable as a PNG sheet, and turn the sheet
back into the C that defines it.

    tools/font.py extract <executable> <fonts.txt> <name> <sheet.png>
    tools/font.py build <fonts.txt> <name> <sheet.png> <glyphs.inc>

The Japanese version draws its kanji, kana and symbols from a font in its
executable: 12x11 glyphs of one bit per pixel, each row two bytes with the
leftmost pixel in the first byte's bit 7 (the last four bits are unused).
The game's data can't be in the repository, so the build takes the font
from the disc as the rest of the executable: `make generate` extracts each
table into assets/<version>/<name>.png, and the build converts the PNG into
build/<version>/assets/<name>.inc, the initializer of a SjisGlyph array
(src/main/ui/str_util.c) with one {row, ...} per glyph.

config/<version>/fonts.txt lists the tables: a name, the table's offset in
the executable and its number of glyphs. The sheet has 94 glyphs a row, as
many as a row of the JIS table: a row of the kanji sheet is one row of JIS
level 1. Ink is black on white; when the sheet is edited, any dark pixel is
ink, whatever the PNG's format.
"""

import sys

import png

GLYPH_WIDTH = 12
GLYPH_HEIGHT = 11
# bytes per row of a glyph, and per glyph
ROW_BYTES = 2
GLYPH_BYTES = GLYPH_HEIGHT * ROW_BYTES
# glyphs per row of the sheet: a row of the JIS table
COLUMNS = 94

# the sheet's palette: paper, then ink
PALETTE = [(0xFF, 0xFF, 0xFF), (0x00, 0x00, 0x00)]


def read_table(fonts: str, name: str) -> tuple:
    """(offset, glyphs) of the table NAME in the list FONTS."""
    with open(fonts) as f:
        for line in f:
            fields = line.split("#", 1)[0].split()
            if fields and fields[0] == name:
                return int(fields[1], 0), int(fields[2], 0)
    sys.exit(f"{fonts}: no font table {name}")


def sheet_size(glyphs: int) -> tuple:
    """The (width, height) in pixels of a sheet of GLYPHS glyphs."""
    rows = (glyphs + COLUMNS - 1) // COLUMNS
    return COLUMNS * GLYPH_WIDTH, rows * GLYPH_HEIGHT


def glyph_origin(index: int) -> tuple:
    """The (x, y) of glyph INDEX's top left pixel on the sheet."""
    return index % COLUMNS * GLYPH_WIDTH, index // COLUMNS * GLYPH_HEIGHT


def extract(exe: str, fonts: str, name: str, out: str) -> None:
    offset, glyphs = read_table(fonts, name)
    with open(exe, "rb") as f:
        f.seek(offset)
        data = f.read(glyphs * GLYPH_BYTES)
    if len(data) != glyphs * GLYPH_BYTES:
        sys.exit(f"{exe}: the font table {name} runs past the end")
    width, height = sheet_size(glyphs)
    pixels = [[0] * width for _ in range(height)]
    for index in range(glyphs):
        x0, y0 = glyph_origin(index)
        for row in range(GLYPH_HEIGHT):
            at = index * GLYPH_BYTES + row * ROW_BYTES
            bits = int.from_bytes(data[at:at + ROW_BYTES], "big")
            if bits & ((1 << (8 * ROW_BYTES - GLYPH_WIDTH)) - 1):
                sys.exit(f"{exe}: glyph {index} of {name} has ink past its {GLYPH_WIDTH} columns")
            for col in range(GLYPH_WIDTH):
                pixels[y0 + row][x0 + col] = bits >> (8 * ROW_BYTES - 1 - col) & 1
    with open(out, "wb") as f:
        png.Writer(width, height, palette=PALETTE, bitdepth=1).write(f, pixels)


def build(fonts: str, name: str, sheet: str, out: str) -> None:
    _, glyphs = read_table(fonts, name)
    width, height, rows, _ = png.Reader(filename=sheet).asRGBA8()
    if (width, height) != sheet_size(glyphs):
        sys.exit(f"{sheet}: {width}x{height} pixels, but {glyphs} glyphs make a "
                 "{}x{} sheet".format(*sheet_size(glyphs)))
    # ink: dark and not transparent
    ink = [[r[4 * x + 3] >= 0x80 and sum(r[4 * x:4 * x + 3]) < 3 * 0x80 for x in range(width)]
           for r in rows]
    lines = []
    for index in range(glyphs):
        x0, y0 = glyph_origin(index)
        cells = []
        for row in range(GLYPH_HEIGHT):
            bits = 0
            for col in range(GLYPH_WIDTH):
                bits |= ink[y0 + row][x0 + col] << (8 * ROW_BYTES - 1 - col)
            cells.append("{ " + ", ".join(f"0x{b:02X}" for b in bits.to_bytes(ROW_BYTES, "big")) + " }")
        lines.append(f"/* {index:4} */ {{ {', '.join(cells)} }},\n")
    for index in range(glyphs, (height // GLYPH_HEIGHT) * COLUMNS):
        x0, y0 = glyph_origin(index)
        if any(any(ink[y0 + row][x0:x0 + GLYPH_WIDTH]) for row in range(GLYPH_HEIGHT)):
            sys.exit(f"{sheet}: ink in cell {index}, past the font's {glyphs} glyphs")
    with open(out, "w") as f:
        f.write(f"/* {name}: generated by tools/font.py from {sheet} */\n")
        f.writelines(lines)


def main() -> None:
    if len(sys.argv) == 6 and sys.argv[1] == "extract":
        extract(*sys.argv[2:])
    elif len(sys.argv) == 6 and sys.argv[1] == "build":
        build(*sys.argv[2:])
    else:
        sys.exit(__doc__.split("\n\n")[1])


if __name__ == "__main__":
    main()
